export const CONTACT_EMAIL = "contact@wakyou-trading.com";

export const copy = {
  ja: {
    lang: "JA",
    meta: {
      home: "株式会社和橋商事 | 日本と世界をつなぐビジネスパートナー",
      business: "事業内容 | 株式会社和橋商事",
      company: "企業情報 | 株式会社和橋商事",
      profile: "代表メッセージ | 株式会社和橋商事",
      contact: "お問い合わせ | 株式会社和橋商事",
    },
    nav: { home: "ホーム", business: "事業内容", company: "企業情報", profile: "代表メッセージ", contact: "お問い合わせ" },
    common: { details: "詳しく見る", contact: "お問い合わせ", back: "ホームへ戻る", pageEyebrow: "WAKYOU TRADING" },
    home: {
      heroEyebrow: "DIGITAL × GLOBAL BUSINESS",
      heroTitle: "Connecting Japan\nwith Global Markets.",
      heroLead: "日本と世界をつなぐ、\nデジタル時代のビジネスパートナー。",
      heroSub: "International Trading, Cross-border E-Commerce & Business Solutions",
      primary: "事業内容を見る",
      servicesLabel: "OUR BUSINESS",
      servicesTitle: "オンラインとテクノロジーで、\n国境を越えるビジネスを支える。",
      servicesIntro: "貿易、EC、クリエイター領域を一つのネットワークとして捉え、企業の新しい市場づくりを支援します。",
      services: [
        { id: "trading", title: "International Trading", subtitle: "国際貿易", text: "日本と世界をつなぎ、商品・ブランド・市場の可能性を広げます。" },
        { id: "ec", title: "Cross-border EC Solutions", subtitle: "越境ECソリューション", text: "データと運営力で、ブランドの海外展開と継続的な成長を支援します。" },
        { id: "creator", title: "Creator & Live Commerce", subtitle: "クリエイター＆ライブコマース", text: "クリエイターとブランドをつなぎ、新しい購買体験を創造します。" },
      ],
      positioningLabel: "OUR POSITION",
      positioningTitle: "A trading company built for the digital economy.",
      positioningText: "私たちは、商品を運ぶだけの商社ではありません。IT、EC、デジタルマーケティングを組み合わせ、国境を越えるビジネスの仕組みそのものを設計します。",
      points: ["グローバルな調達・販売ネットワーク", "ECプラットフォームを活用した市場開拓", "データとテクノロジーを生かした事業支援"],
      philosophyLabel: "COMPANY PHILOSOPHY",
      philosophyTitle: "信頼をつなぎ、価値を創る。",
      philosophyText: "人と人、企業と企業、日本と世界をつなぐ架け橋となり、誠実な取引と革新的なサービスを通じて、お客様とともに新たな価値を創造します。",
      ctaTitle: "国境を越えるビジネスを、\nともに始めませんか。",
      ctaText: "商品、ブランド、EC運営、海外展開についてお気軽にご相談ください。",
    },
    business: {
      eyebrow: "OUR BUSINESS",
      title: "事業内容",
      intro: "国際貿易を中核に、越境ECとクリエイター領域を組み合わせ、企業の市場開拓を一気通貫で支援します。",
      sections: [
        { id: "trading", no: "01", title: "International Trading", ja: "国際貿易 / クロスボーダー取引", text: "日本と海外の企業・商品・市場をつなぎ、調達から販売まで柔軟に対応します。オンライン販売を前提とした商品選定や市場開拓にも強みがあります。", items: ["日本商品の輸出", "日本ブランド代理", "中国商品の輸入", "国際貿易", "卸売・小売", "海外販路開拓"] },
        { id: "ec", no: "02", title: "EC Business Solutions", ja: "EC事業ソリューション", text: "EC店舗の立ち上げから運営、商品企画、海外ブランドの日本進出まで、実務と戦略の両面から伴走します。", items: ["EC店舗運営", "Amazon・楽天運営", "商品企画", "海外ブランドの日本市場参入", "日本・中国市場コンサルティング", "越境EC・事業戦略コンサルティング"] },
        { id: "creator", no: "03", title: "Creator & Live Commerce", ja: "クリエイター＆ライブコマース", text: "クリエイターの成長とブランドの販売活動をつなぎ、ライブ配信を活用した新しい商流づくりを支援します。", items: ["クリエイター募集・育成", "Creator Management", "MCNコンサルティング", "ライブ配信運営相談", "TikTokライブ相談", "ライブコマース支援"] },
      ],
      ctaTitle: "事業に合わせた最適な進め方をご提案します。",
    },
    company: {
      eyebrow: "COMPANY",
      title: "企業情報",
      intro: "信頼を起点に、デジタルとグローバルを結ぶ新しい商社の形を追求します。",
      philosophyLabel: "COMPANY PHILOSOPHY",
      philosophyTitle: "信頼をつなぎ、価値を創る。",
      philosophyText: "私たちは、人と人、企業と企業、日本と世界をつなぐ架け橋となり、誠実な取引と革新的なサービスを通じて、お客様とともに新たな価値を創造します。国際貿易、越境EC、ビジネスコンサルティング、クリエイター支援事業を通じ、持続可能な社会と豊かな未来の実現に貢献してまいります。",
      missionTitle: "MISSION",
      mission: "日本と世界をつなぎ、新たなビジネス価値を創造する。",
      visionTitle: "VISION",
      vision: "世界で信頼される総合商社・ビジネスソリューション企業を目指す。",
      valuesTitle: "VALUE",
      values: [
        { title: "誠実 / Integrity", text: "誠実な姿勢で、長期的な信頼関係を築きます。" },
        { title: "挑戦 / Innovation", text: "デジタル技術を生かし、新しい商流に挑み続けます。" },
        { title: "共創 / Partnership", text: "お客様、パートナーとともに成長します。" },
        { title: "国際性 / Global Perspective", text: "国際的な視点で市場と機会をつなぎます。" },
      ],
      overviewTitle: "COMPANY OVERVIEW",
      overview: [["会社名", "株式会社和橋商事"], ["英文名", "Wakyou Trading Co., Ltd."], ["代表取締役", "飯島 航"], ["事業内容", "国際貿易、卸売・小売、越境EC、EC運営支援、ビジネスコンサルティング、クリエイター・ライブコマース支援"]],
    },
    profile: {
      eyebrow: "PRESIDENT MESSAGE",
      title: "代表メッセージ",
      intro: "ITとビジネスを融合し、従来の商社の枠を超えた価値を創造します。",
      name: "代表取締役　飯島 航",
      message: [
        "平素より株式会社和橋商事をご支援いただき、誠にありがとうございます。",
        "和橋商事は、「信頼をつなぎ、価値を創る。」という理念のもと、日本と世界を結ぶ架け橋として、お客様とともに歩み続けています。",
        "国際貿易や越境ECを取り巻く環境は、デジタル技術の進歩と新しいビジネスモデルの誕生により大きく変化しています。私たちは、国際貿易、小売・卸売、越境EC、EC運営支援、貿易コンサルティング、そしてライブコマースやクリエイター事業に関するコンサルティングを通じ、お客様一人ひとりの課題に寄り添い、最適なソリューションを提供してまいります。",
        "私は情報技術分野を学び、システム開発やネットワーク技術などの知識を培ってまいりました。ITとビジネスを融合させることで、従来の商社の枠を超えた新しい価値を創造できると信じています。",
        "企業経営において最も大切なのは、信頼です。一つひとつの仕事に誠実に向き合い、長期的な価値を提供してまいります。今後とも変わらぬご支援を賜りますよう、よろしくお願い申し上げます。",
      ],
      profileLabel: "PROFILE",
      profileTitle: "飯島 航",
      role: "代表取締役",
      bio: "1999年生まれ。情報技術分野を学び、IT・ネットワーク・ソフトウェア開発を中心に専門知識を修得。Javaプログラミング、ネットワーク、データベースなど複数の資格を取得。現在は株式会社和橋商事の代表取締役として、国際貿易、越境EC、デジタルビジネスの発展に取り組み、日本と海外を結ぶ新たなビジネスモデルの構築を目指している。",
      personalLabel: "PERSONAL",
      personal: ["読書", "IT・AIなど最新技術の研究", "スポーツ", "国内外の経済・ビジネス情報の収集", "地域活動・ボランティア"],
      mottoLabel: "座右の銘",
      motto: "信頼はすべてのビジネスの原点。",
    },
    contact: {
      eyebrow: "CONTACT",
      title: "お問い合わせ",
      intro: "国際貿易、越境EC、EC運営、海外展開、クリエイター事業に関するご相談を承ります。",
      formTitle: "ご相談内容をお聞かせください",
      fields: { company: "会社名", name: "お名前", email: "メールアドレス", category: "お問い合わせ種別", message: "お問い合わせ内容", consent: "個人情報の取り扱いに同意します。", submit: "メールを作成する" },
      categories: ["国際貿易・卸売", "越境EC・EC運営", "市場参入・事業相談", "クリエイター・ライブコマース", "その他"],
      success: "メールソフトを開きます。送信内容をご確認ください。",
      directTitle: "メールでのお問い合わせ",
      directText: "直接メールでのご相談も承ります。",
      note: "通常2営業日以内にご連絡いたします。",
    },
  },
  zh: {
    lang: "中文",
    meta: { home: "株式会社和橋商事 | 连接日本与全球市场", business: "业务内容 | 株式会社和橋商事", company: "公司信息 | 株式会社和橋商事", profile: "社长致辞 | 株式会社和橋商事", contact: "联系我们 | 株式会社和橋商事" },
    nav: { home: "首页", business: "业务内容", company: "公司信息", profile: "社长致辞", contact: "联系我们" },
    common: { details: "了解详情", contact: "联系我们", back: "返回首页", pageEyebrow: "WAKYOU TRADING" },
    home: {
      heroEyebrow: "DIGITAL × GLOBAL BUSINESS", heroTitle: "Connecting Japan\nwith Global Markets.", heroLead: "连接日本与世界，\n成为数字时代的商业伙伴。", heroSub: "International Trading, Cross-border E-Commerce & Business Solutions", primary: "查看业务内容",
      servicesLabel: "OUR BUSINESS", servicesTitle: "以线上能力与科技，\n推动跨境商业增长。", servicesIntro: "将贸易、电商与创作者经济连接成一个商业网络，帮助企业持续开拓新市场。",
      services: [
        { id: "trading", title: "International Trading", subtitle: "国际贸易", text: "连接日本与全球市场，拓展商品、品牌与市场的更多可能。" },
        { id: "ec", title: "Cross-border EC Solutions", subtitle: "跨境电商解决方案", text: "以数据与运营能力，支持品牌出海和长期增长。" },
        { id: "creator", title: "Creator & Live Commerce", subtitle: "创作者与直播电商", text: "连接创作者与品牌，创造新的消费体验。" },
      ],
      positioningLabel: "OUR POSITION", positioningTitle: "A trading company built for the digital economy.", positioningText: "我们不只是一家负责商品流通的贸易公司。我们将IT、电商和数字营销结合起来，设计真正适应跨境业务发展的商业体系。", points: ["全球采购与销售网络", "依托电商平台开拓新市场", "以数据和技术支持企业增长"],
      philosophyLabel: "COMPANY PHILOSOPHY", philosophyTitle: "连接信任，创造价值。", philosophyText: "我们希望成为连接人与人、企业与企业、日本与世界之间的桥梁，通过诚信经营与持续创新，与客户共同创造新的价值。",
      ctaTitle: "让我们一起，\n开启跨境商业的新机会。", ctaText: "欢迎就商品、品牌、电商运营及海外市场拓展与我们联系。",
    },
    business: {
      eyebrow: "OUR BUSINESS", title: "业务内容", intro: "以国际贸易为核心，融合跨境电商与创作者经济，为企业提供贯穿市场开拓全流程的支持。",
      sections: [
        { id: "trading", no: "01", title: "International Trading", ja: "国际贸易 / 跨境交易", text: "连接日本与海外企业、商品及市场，从采购到销售提供灵活支持，并关注线上销售导向的选品与市场开拓。", items: ["日本商品出口", "日本品牌代理", "中国商品进口", "国际贸易", "批发与零售", "海外销售渠道拓展"] },
        { id: "ec", no: "02", title: "EC Business Solutions", ja: "电商业务解决方案", text: "从店铺搭建、运营、商品策划到海外品牌进入日本市场，在执行和战略层面持续陪伴企业成长。", items: ["电商店铺运营", "Amazon与乐天运营", "商品策划", "海外品牌进入日本市场", "日本与中国市场咨询", "跨境电商与商业战略咨询"] },
        { id: "creator", no: "03", title: "Creator & Live Commerce", ja: "创作者与直播电商", text: "连接创作者成长与品牌销售，借助直播和内容创造新的商业通路。", items: ["主播招募与培训", "Creator Management", "MCN咨询", "直播运营咨询", "TikTok直播咨询", "直播带货支持"] },
      ], ctaTitle: "我们会根据您的业务，提供最合适的推进方案。",
    },
    company: {
      eyebrow: "COMPANY", title: "公司信息", intro: "以信任为起点，探索连接数字科技与全球市场的新型商贸公司。", philosophyLabel: "COMPANY PHILOSOPHY", philosophyTitle: "连接信任，创造价值。", philosophyText: "我们希望成为连接人与人、企业与企业、日本与世界之间的桥梁。通过诚信经营、专业服务和持续创新，为客户创造价值，为合作伙伴创造机会，为社会创造贡献。依托国际贸易、跨境电商、商业咨询以及创作者经济等业务，不断推动商业合作的发展，实现企业与客户共同成长。", missionTitle: "MISSION", mission: "连接日本与世界，创造新的商业价值。", visionTitle: "VISION", vision: "成为值得全球信赖的国际商贸与商业解决方案企业。", valuesTitle: "VALUE", values: [
        { title: "诚信 / Integrity", text: "诚信经营，以信任建立长期合作。" }, { title: "创新 / Innovation", text: "拥抱数字技术，不断突破传统商业模式。" }, { title: "共创 / Partnership", text: "与客户、合作伙伴共同成长。" }, { title: "国际视野 / Global Perspective", text: "以全球视野连接市场与机会。" },
      ], overviewTitle: "COMPANY OVERVIEW", overview: [["公司名称", "株式会社和橋商事"], ["英文名称", "Wakyou Trading Co., Ltd."], ["代表董事", "飯島 航"], ["业务内容", "国际贸易、批发零售、跨境电商、电商运营支持、商业咨询、创作者及直播电商支持"]],
    },
    profile: {
      eyebrow: "PRESIDENT MESSAGE", title: "社长致辞", intro: "融合IT与商业，创造超越传统商社框架的新价值。", name: "代表董事　飯島 航",
      message: ["衷心感谢各位长期以来对株式会社和橋商事的支持。", "和橋商事秉持“连接信任，创造价值”的理念，努力成为连接日本与世界的桥梁，与客户携手前行。", "随着数字技术和新商业模式的发展，国际贸易与跨境电商正在快速变化。我们通过国际贸易、批发零售、跨境电商、电商运营、贸易咨询，以及直播电商与创作者业务咨询，为每一位客户提供贴近实际需求的解决方案。", "我曾在信息技术领域学习系统开发、网络技术等专业知识。我相信，将IT与商业相融合，能够创造超越传统商社框架的新价值。", "企业经营最重要的是信任。我们将真诚对待每一项工作，持续提供长期价值。今后也敬请继续支持株式会社和橋商事。"],
      profileLabel: "PROFILE", profileTitle: "飯島 航", role: "代表董事", bio: "1999年出生。学习信息技术领域专业知识，重点掌握IT、网络和软件开发，并取得Java编程、网络、数据库等多项资格。现任株式会社和橋商事代表董事，致力于国际贸易、跨境电商和数字商业的发展，积极构建连接日本与海外的新型商业模式。", personalLabel: "PERSONAL", personal: ["阅读", "研究IT、AI等新技术", "体育运动", "关注国内外经济与商业资讯", "社区活动与志愿服务"], mottoLabel: "座右铭", motto: "信任是一切商业的起点。",
    },
    contact: {
      eyebrow: "CONTACT", title: "联系我们", intro: "欢迎就国际贸易、跨境电商、电商运营、海外市场拓展及创作者业务与我们咨询。", formTitle: "请告诉我们您的需求", fields: { company: "公司名称", name: "姓名", email: "邮箱", category: "咨询类别", message: "咨询内容", consent: "我同意个人信息处理条款。", submit: "创建咨询邮件" }, categories: ["国际贸易与批发", "跨境电商与店铺运营", "市场进入与商业咨询", "创作者与直播电商", "其他"], success: "正在打开邮件客户端，请确认内容后发送。", directTitle: "邮件咨询", directText: "也可直接发送邮件与我们联系。", note: "我们通常会在2个工作日内回复。",
    },
  },
  en: {
    lang: "EN",
    meta: { home: "Wakyou Trading | Connecting Japan with Global Markets", business: "Our Business | Wakyou Trading", company: "Company | Wakyou Trading", profile: "President Message | Wakyou Trading", contact: "Contact | Wakyou Trading" },
    nav: { home: "Home", business: "Business", company: "Company", profile: "President", contact: "Contact" },
    common: { details: "Learn more", contact: "Contact us", back: "Back to home", pageEyebrow: "WAKYOU TRADING" },
    home: {
      heroEyebrow: "DIGITAL × GLOBAL BUSINESS", heroTitle: "Connecting Japan\nwith Global Markets.", heroLead: "Your business partner for\nthe connected economy.", heroSub: "International Trading, Cross-border E-Commerce & Business Solutions", primary: "Explore our business",
      servicesLabel: "OUR BUSINESS", servicesTitle: "Powering cross-border growth\nthrough commerce and technology.", servicesIntro: "We connect trading, e-commerce and the creator economy as one business network, helping companies build new markets.",
      services: [
        { id: "trading", title: "International Trading", subtitle: "Global Trade", text: "Connecting Japan with global products, brands and market opportunities." },
        { id: "ec", title: "Cross-border EC Solutions", subtitle: "E-Commerce Growth", text: "Helping brands expand internationally through data and hands-on operations." },
        { id: "creator", title: "Creator & Live Commerce", subtitle: "Creator Economy", text: "Connecting creators and brands to build new buying experiences." },
      ],
      positioningLabel: "OUR POSITION", positioningTitle: "A trading company built for the digital economy.", positioningText: "We do more than move products. By combining IT, e-commerce and digital marketing, we design the systems that make cross-border business work.", points: ["Global sourcing and sales networks", "Market development through e-commerce platforms", "Business growth powered by data and technology"],
      philosophyLabel: "COMPANY PHILOSOPHY", philosophyTitle: "Connecting trust. Creating value.", philosophyText: "We bridge people, businesses, Japan and the world—creating new value with our clients through honest trading and forward-looking services.",
      ctaTitle: "Ready to build business\nbeyond borders?", ctaText: "Talk to us about products, brands, e-commerce operations and international expansion.",
    },
    business: {
      eyebrow: "OUR BUSINESS", title: "Business", intro: "With international trading at our core, we combine cross-border e-commerce and creator commerce to support market development end to end.",
      sections: [
        { id: "trading", no: "01", title: "International Trading", ja: "Global & Cross-border Trade", text: "We connect companies, products and markets across Japan and overseas, supporting flexible sourcing and sales with a digital-first market perspective.", items: ["Export of Japanese products", "Japanese brand representation", "Import of Chinese products", "International trade", "Wholesale and retail", "Overseas channel development"] },
        { id: "ec", no: "02", title: "EC Business Solutions", ja: "E-Commerce Consulting", text: "From store launches and operations to product planning and Japan market entry, we support both execution and strategy.", items: ["EC store operations", "Amazon and Rakuten operations", "Product planning", "Japan market entry", "Japan and China market consulting", "Cross-border EC and business strategy"] },
        { id: "creator", no: "03", title: "Creator & Live Commerce", ja: "Creator Business", text: "We connect creator growth with brand sales and help build new commercial channels through content and live streaming.", items: ["Creator recruitment and training", "Creator management", "MCN consulting", "Live-stream operations consulting", "TikTok LIVE consulting", "Live commerce support"] },
      ], ctaTitle: "Let’s find the right path for your business.",
    },
    company: {
      eyebrow: "COMPANY", title: "Company", intro: "Starting with trust, we are building a new kind of trading company that connects digital technology and global markets.", philosophyLabel: "COMPANY PHILOSOPHY", philosophyTitle: "Connecting trust. Creating value.", philosophyText: "We aim to be a bridge between people, companies, Japan and the world. Through honest business, professional service and continuous innovation, we create value for clients, opportunities for partners and a positive contribution to society.", missionTitle: "MISSION", mission: "Connect Japan with the world and create new business value.", visionTitle: "VISION", vision: "To become a globally trusted trading and business solutions company.", valuesTitle: "VALUE", values: [
        { title: "Integrity", text: "We build lasting partnerships through honesty and trust." }, { title: "Innovation", text: "We use digital technology to challenge old business models." }, { title: "Partnership", text: "We grow together with our clients and partners." }, { title: "Global Perspective", text: "We connect markets and opportunities with a global outlook." },
      ], overviewTitle: "COMPANY OVERVIEW", overview: [["Company", "Wakyou Trading Co., Ltd."], ["Japanese Name", "株式会社和橋商事"], ["Representative Director", "Wataru Iijima"], ["Business", "International trading, wholesale and retail, cross-border EC, EC operations, business consulting, creator and live commerce support"]],
    },
    profile: {
      eyebrow: "PRESIDENT MESSAGE", title: "President Message", intro: "Combining IT and business to create value beyond the traditional trading-company model.", name: "Wataru Iijima, Representative Director",
      message: ["Thank you for your continued support of Wakyou Trading Co., Ltd.", "Guided by our philosophy, “Connecting trust. Creating value,” we continue to walk alongside our clients as a bridge between Japan and the world.", "International trade and cross-border e-commerce are changing rapidly as digital technology advances and new business models emerge. Through trading, wholesale and retail, cross-border EC, EC operations, trade consulting, live commerce and creator-business consulting, we provide solutions tailored to each client’s needs.", "My background is in information technology, including system development and network technology. I believe combining IT and business enables us to create value beyond the traditional boundaries of a trading company.", "Trust is the foundation of every business. We approach every project with integrity and remain committed to delivering long-term value."],
      profileLabel: "PROFILE", profileTitle: "Wataru Iijima", role: "Representative Director", bio: "Born in 1999. Studied information technology with a focus on IT, networks and software development, earning qualifications in Java programming, networking and databases. Today, he leads Wakyou Trading and works to develop international trading, cross-border e-commerce and digital business models connecting Japan with overseas markets.", personalLabel: "PERSONAL", personal: ["Reading", "Researching IT, AI and emerging technology", "Sports", "Following global economics and business", "Community and volunteer activities"], mottoLabel: "MOTTO", motto: "Trust is the starting point of every business.",
    },
    contact: {
      eyebrow: "CONTACT", title: "Contact", intro: "Talk to us about international trading, cross-border e-commerce, EC operations, market entry and creator business.", formTitle: "Tell us about your project", fields: { company: "Company", name: "Name", email: "Email", category: "Inquiry type", message: "Message", consent: "I agree to the handling of my personal information.", submit: "Create inquiry email" }, categories: ["International trading & wholesale", "Cross-border EC & operations", "Market entry & business consulting", "Creator & live commerce", "Other"], success: "Opening your email app. Please review the message before sending.", directTitle: "Email us directly", directText: "You can also contact us directly by email.", note: "We usually respond within two business days.",
    },
  },
};
